local addonName, addon = ...

-- Set up all emoticons
function addon:SetupDefaultEmojis()
    local x = self:GetEmojiSizeString()

    -- Normal Emojis
    self:AddSmiley(":angry:", self:TextureString(addon.M..[[Emojis\Angry.tga]], x))
    self:AddSmiley(":blush:", self:TextureString(addon.M..[[Emojis\Blush.tga]], x))
    self:AddSmiley(":broken_heart:", self:TextureString(addon.M..[[Emojis\BrokenHeart.tga]], x))
    self:AddSmiley(":call_me:", self:TextureString(addon.M..[[Emojis\CallMe.tga]], x))
    self:AddSmiley(":cry:", self:TextureString(addon.M..[[Emojis\Cry.tga]], x))
    self:AddSmiley(":grin:", self:TextureString(addon.M..[[Emojis\Grin.tga]], x))
    self:AddSmiley(":heart:", self:TextureString(addon.M..[[Emojis\Heart.tga]], x))
    self:AddSmiley(":heart_eyes:", self:TextureString(addon.M..[[Emojis\HeartEyes.tga]], x))
    self:AddSmiley(":joy:", self:TextureString(addon.M..[[Emojis\Joy.tga]], x))
    self:AddSmiley(":middle_finger:", self:TextureString(addon.M..[[Emojis\MiddleFinger.tga]], x))
    self:AddSmiley(":ok_hand:", self:TextureString(addon.M..[[Emojis\OkHand.tga]], x))
    self:AddSmiley(":open_mouth:", self:TextureString(addon.M..[[Emojis\OpenMouth.tga]], x))
    self:AddSmiley(":poop:", self:TextureString(addon.M..[[Emojis\Poop.tga]], x))
    self:AddSmiley(":rage:", self:TextureString(addon.M..[[Emojis\Rage.tga]], x))
    self:AddSmiley(":scream:", self:TextureString(addon.M..[[Emojis\Scream.tga]], x))
    self:AddSmiley(":scream_cat:", self:TextureString(addon.M..[[Emojis\ScreamCat.tga]], x))
    self:AddSmiley(":semi_colon:", self:TextureString(addon.M..[[Emojis\SemiColon.tga]], x))
    self:AddSmiley(":slight_frown:", self:TextureString(addon.M..[[Emojis\SlightFrown.tga]], x))
    self:AddSmiley(":smile:", self:TextureString(addon.M..[[Emojis\Smile.tga]], x))
    self:AddSmiley(":smirk:", self:TextureString(addon.M..[[Emojis\Smirk.tga]], x))
    self:AddSmiley(":sob:", self:TextureString(addon.M..[[Emojis\Sob.tga]], x))
    self:AddSmiley(":stuck_out_tongue:", self:TextureString(addon.M..[[Emojis\StuckOutTongue.tga]], x))
    self:AddSmiley(":stuck_out_tongue_closed_eyes:", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.tga]], x))
    self:AddSmiley(":sunglasses:", self:TextureString(addon.M..[[Emojis\Sunglasses.tga]], x))
    self:AddSmiley(":thinking:", self:TextureString(addon.M..[[Emojis\Thinking.tga]], x))
    self:AddSmiley(":thumbs_up:", self:TextureString(addon.M..[[Emojis\ThumbsUp.tga]], x))
    self:AddSmiley(":wink:", self:TextureString(addon.M..[[Emojis\Wink.tga]], x))
    self:AddSmiley(":zzz:", self:TextureString(addon.M..[[Emojis\ZZZ.tga]], x))

    -- Pepe Emojis
    self:AddSmiley(":peepoalliance:", self:TextureString(addon.M..[[PepeEmojis\PeepoAlliance.tga]], x))
    self:AddSmiley(":peepohorde:", self:TextureString(addon.M..[[PepeEmojis\PeepoHorde.tga]], x))
    self:AddSmiley(":pepepanties:", self:TextureString(addon.M..[[PepeEmojis\PepePanties.tga]], x))
    self:AddSmiley(":pepewarlock:", self:TextureString(addon.M..[[PepeEmojis\PepeWarlock.tga]], x))

    -- Discord Emojis
    self:AddSmiley(":4head:", self:TextureString(addon.M..[[DiscordEmojis\4Head.tga]], x))
    self:AddSmiley(":5head:", self:TextureString(addon.M..[[DiscordEmojis\5Head.tga]], x))
    self:AddSmiley(":ambessalove:", self:TextureString(addon.M..[[DiscordEmojis\AmbessaLove.tga]], x))
    self:AddSmiley(":andalusiancrush:", self:TextureString(addon.M..[[DiscordEmojis\AndalusianCrush.tga]], x))
    self:AddSmiley(":anele:", self:TextureString(addon.M..[[DiscordEmojis\ANELE.tga]], x))
    self:AddSmiley(":anotherrecord:", self:TextureString(addon.M..[[DiscordEmojis\AnotherRecord.tga]], x))
    self:AddSmiley(":argieb8:", self:TextureString(addon.M..[[DiscordEmojis\ArgieB8.tga]], x))
    self:AddSmiley(":arsonnosexy:", self:TextureString(addon.M..[[DiscordEmojis\ArsonNoSexy.tga]], x))
    self:AddSmiley(":asexualpride:", self:TextureString(addon.M..[[DiscordEmojis\AsexualPride.tga]], x))
    self:AddSmiley(":asianglow:", self:TextureString(addon.M..[[DiscordEmojis\AsianGlow.tga]], x))
    self:AddSmiley(":babyrage:", self:TextureString(addon.M..[[DiscordEmojis\BabyRage.tga]], x))
    self:AddSmiley(":bangboobounce:", self:TextureString(addon.M..[[DiscordEmojis\BangbooBounce.tga]], x))
    self:AddSmiley(":batchest:", self:TextureString(addon.M..[[DiscordEmojis\BatChest.tga]], x))
    self:AddSmiley(":bcwarrior:", self:TextureString(addon.M..[[DiscordEmojis\BCWarrior.tga]], x))
    self:AddSmiley(":begwan:", self:TextureString(addon.M..[[DiscordEmojis\BegWan.tga]], x))
    self:AddSmiley(":bigbrother:", self:TextureString(addon.M..[[DiscordEmojis\BigBrother.tga]], x))
    self:AddSmiley(":bigphish:", self:TextureString(addon.M..[[DiscordEmojis\BigPhish.tga]], x))
    self:AddSmiley(":bigsad:", self:TextureString(addon.M..[[DiscordEmojis\BigSad.tga]], x))
    self:AddSmiley(":bisexualpride:", self:TextureString(addon.M..[[DiscordEmojis\BisexualPride.tga]], x))
    self:AddSmiley(":blacklivesmatter:", self:TextureString(addon.M..[[DiscordEmojis\BlackLivesMatter.tga]], x))
    self:AddSmiley(":blargnaut:", self:TextureString(addon.M..[[DiscordEmojis\BlargNaut.tga]], x))
    self:AddSmiley(":bleedpurple:", self:TextureString(addon.M..[[DiscordEmojis\BleedPurple.tga]], x))
    self:AddSmiley(":bloodtrail:", self:TextureString(addon.M..[[DiscordEmojis\BloodTrail.tga]], x))
    self:AddSmiley(":bop:", self:TextureString(addon.M..[[DiscordEmojis\BOP.tga]], x))
    self:AddSmiley(":brain:", self:TextureString(addon.M..[[DiscordEmojis\Brain.tga]], x))
    self:AddSmiley(":brainslug:", self:TextureString(addon.M..[[DiscordEmojis\BrainSlug.tga]], x))
    self:AddSmiley(":bratchat:", self:TextureString(addon.M..[[DiscordEmojis\BratChat.tga]], x))
    self:AddSmiley(":brokeback:", self:TextureString(addon.M..[[DiscordEmojis\BrokeBack.tga]], x))
    self:AddSmiley(":buddhabar:", self:TextureString(addon.M..[[DiscordEmojis\BuddhaBar.tga]], x))
    self:AddSmiley(":caitlyns:", self:TextureString(addon.M..[[DiscordEmojis\Caitlyns.tga]], x))
    self:AddSmiley(":caitthinking:", self:TextureString(addon.M..[[DiscordEmojis\CaitThinking.tga]], x))
    self:AddSmiley(":carlsmile:", self:TextureString(addon.M..[[DiscordEmojis\CarlSmile.tga]], x))
    self:AddSmiley(":cheffrank:", self:TextureString(addon.M..[[DiscordEmojis\ChefFrank.tga]], x))
    self:AddSmiley(":chewyyay:", self:TextureString(addon.M..[[DiscordEmojis\ChewyYAY.tga]], x))
    self:AddSmiley(":cinheimer:", self:TextureString(addon.M..[[DiscordEmojis\Cinheimer.tga]], x))
    self:AddSmiley(":cmonbruh:", self:TextureString(addon.M..[[DiscordEmojis\CmonBruh.tga]], x))
    self:AddSmiley(":coolcat:", self:TextureString(addon.M..[[DiscordEmojis\CoolCat.tga]], x))
    self:AddSmiley(":coolstorybob:", self:TextureString(addon.M..[[DiscordEmojis\CoolStoryBob.tga]], x))
    self:AddSmiley(":copythis:", self:TextureString(addon.M..[[DiscordEmojis\CopyThis.tga]], x))
    self:AddSmiley(":corgiderp:", self:TextureString(addon.M..[[DiscordEmojis\CorgiDerp.tga]], x))
    self:AddSmiley(":crreamawk:", self:TextureString(addon.M..[[DiscordEmojis\CrreamAwk.tga]], x))
    self:AddSmiley(":crythumbsup:", self:TextureString(addon.M..[[DiscordEmojis\CryThumbsUp.tga]], x))
    self:AddSmiley(":cuckcru:", self:TextureString(addon.M..[[DiscordEmojis\CuckCru.tga]], x))
    self:AddSmiley(":curselit:", self:TextureString(addon.M..[[DiscordEmojis\CurseLit.tga]], x))
    self:AddSmiley(":d8style:", self:TextureString(addon.M..[[DiscordEmojis\D8style.tga]], x))
    self:AddSmiley(":daesupply:", self:TextureString(addon.M..[[DiscordEmojis\DAESupply.tga]], x))
    self:AddSmiley(":dansgame:", self:TextureString(addon.M..[[DiscordEmojis\DansGame.tga]], x))
    self:AddSmiley(":darkknight:", self:TextureString(addon.M..[[DiscordEmojis\DarkKnight.tga]], x))
    self:AddSmiley(":darkmode:", self:TextureString(addon.M..[[DiscordEmojis\DarkMode.tga]], x))
    self:AddSmiley(":datsheffy:", self:TextureString(addon.M..[[DiscordEmojis\DatSheffy.tga]], x))
    self:AddSmiley(":dendiface:", self:TextureString(addon.M..[[DiscordEmojis\DendiFace.tga]], x))
    self:AddSmiley(":dinodance:", self:TextureString(addon.M..[[DiscordEmojis\DinoDance.tga]], x))
    self:AddSmiley(":dogface:", self:TextureString(addon.M..[[DiscordEmojis\DogFace.tga]], x))
    self:AddSmiley(":doritoschip:", self:TextureString(addon.M..[[DiscordEmojis\DoritosChip.tga]], x))
    self:AddSmiley(":dududu:", self:TextureString(addon.M..[[DiscordEmojis\duDudu.tga]], x))
    self:AddSmiley(":dxcat:", self:TextureString(addon.M..[[DiscordEmojis\DxCat.tga]], x))
    self:AddSmiley(":facepalm:", self:TextureString(addon.M..[[DiscordEmojis\Facepalm.tga]], x))
    self:AddSmiley(":gigachad:", self:TextureString(addon.M..[[DiscordEmojis\GigaChad.tga]], x))
    self:AddSmiley(":gorlock:", self:TextureString(addon.M..[[DiscordEmojis\Gorlock.tga]], x))
    self:AddSmiley(":harold:", self:TextureString(addon.M..[[DiscordEmojis\Harold.tga]], x))
    self:AddSmiley(":huh:", self:TextureString(addon.M..[[DiscordEmojis\Huh.tga]], x))
    self:AddSmiley(":jebaited:", self:TextureString(addon.M..[[DiscordEmojis\Jebaited.tga]], x))
    self:AddSmiley(":kappa:", self:TextureString(addon.M..[[DiscordEmojis\Kappa.tga]], x))
    self:AddSmiley(":kekw:", self:TextureString(addon.M..[[DiscordEmojis\Kekw.tga]], x))
    self:AddSmiley(":meaw:", self:TextureString(addon.M..[[DiscordEmojis\Meaw.tga]], x))
    self:AddSmiley(":pog:", self:TextureString(addon.M..[[DiscordEmojis\Pog.tga]], x))
    self:AddSmiley(":pogchamp:", self:TextureString(addon.M..[[DiscordEmojis\PogChamp.tga]], x))
    self:AddSmiley(":pogging:", self:TextureString(addon.M..[[DiscordEmojis\Pogging.tga]], x))
    self:AddSmiley(":sadkitty:", self:TextureString(addon.M..[[DiscordEmojis\SadKitty.tga]], x))
    self:AddSmiley(":shocked:", self:TextureString(addon.M..[[DiscordEmojis\Shocked.tga]], x))
    self:AddSmiley(":thonkers:", self:TextureString(addon.M..[[DiscordEmojis\Thonkers.tga]], x))
    self:AddSmiley(":troll:", self:TextureString(addon.M..[[DiscordEmojis\Troll.tga]], x))

    -- Warcraft Emojis
    self:AddSmiley(":alliance:", self:TextureString(addon.M..[[WoWEmojis\Alliance.tga]], x))
    self:AddSmiley(":disenchant:", self:TextureString(addon.M..[[WoWEmojis\Disenchant.tga]], x))
    self:AddSmiley(":druid:", self:TextureString(addon.M..[[WoWEmojis\Druid.tga]], x))
    self:AddSmiley(":feelshordeman:", self:TextureString(addon.M..[[WoWEmojis\FeelsHordeMan.tga]], x))
    self:AddSmiley(":femaledwarf:", self:TextureString(addon.M..[[WoWEmojis\FemaleDwarf.tga]], x))
    self:AddSmiley(":femalegnome:", self:TextureString(addon.M..[[WoWEmojis\FemaleGnome.tga]], x))
    self:AddSmiley(":femalehuman:", self:TextureString(addon.M..[[WoWEmojis\FemaleHuman.tga]], x))
    self:AddSmiley(":femalenightelf:", self:TextureString(addon.M..[[WoWEmojis\FemaleNightelf.tga]], x))
    self:AddSmiley(":femaleorc:", self:TextureString(addon.M..[[WoWEmojis\FemaleOrc.tga]], x))
    self:AddSmiley(":femaletauren:", self:TextureString(addon.M..[[WoWEmojis\FemaleTauren.tga]], x))
    self:AddSmiley(":femaletroll:", self:TextureString(addon.M..[[WoWEmojis\FemaleTroll.tga]], x))
    self:AddSmiley(":femaleundead:", self:TextureString(addon.M..[[WoWEmojis\FemaleUndead.tga]], x))
    self:AddSmiley(":gryphon:", self:TextureString(addon.M..[[WoWEmojis\Gryphon.tga]], x))
    self:AddSmiley(":hogger:", self:TextureString(addon.M..[[WoWEmojis\Hogger.tga]], x))
    self:AddSmiley(":horde:", self:TextureString(addon.M..[[WoWEmojis\Horde.tga]], x))
    self:AddSmiley(":hunter:", self:TextureString(addon.M..[[WoWEmojis\Hunter.tga]], x))
    self:AddSmiley(":kekdwarf:", self:TextureString(addon.M..[[WoWEmojis\KekDwarf.tga]], x))
    self:AddSmiley(":mage:", self:TextureString(addon.M..[[WoWEmojis\Mage.tga]], x))
    self:AddSmiley(":maledwarf:", self:TextureString(addon.M..[[WoWEmojis\MaleDwarf.tga]], x))
    self:AddSmiley(":malegnome:", self:TextureString(addon.M..[[WoWEmojis\MaleGnome.tga]], x))
    self:AddSmiley(":malehuman:", self:TextureString(addon.M..[[WoWEmojis\MaleHuman.tga]], x))
    self:AddSmiley(":malenightelf:", self:TextureString(addon.M..[[WoWEmojis\MaleNightelf.tga]], x))
    self:AddSmiley(":malenightelf2:", self:TextureString(addon.M..[[WoWEmojis\MaleNightelf2.tga]], x))
    self:AddSmiley(":maleorc:", self:TextureString(addon.M..[[WoWEmojis\MaleOrc.tga]], x))
    self:AddSmiley(":maletauren:", self:TextureString(addon.M..[[WoWEmojis\MaleTauren.tga]], x))
    self:AddSmiley(":maletroll:", self:TextureString(addon.M..[[WoWEmojis\MaleTroll.tga]], x))
    self:AddSmiley(":maleundead:", self:TextureString(addon.M..[[WoWEmojis\MaleUndead.tga]], x))
    self:AddSmiley(":metzen:", self:TextureString(addon.M..[[WoWEmojis\Metzen.tga]], x))
    self:AddSmiley(":moonkin:", self:TextureString(addon.M..[[WoWEmojis\Moonkin.tga]], x))
    self:AddSmiley(":murloc:", self:TextureString(addon.M..[[WoWEmojis\Murloc.tga]], x))
    self:AddSmiley(":omegawow:", self:TextureString(addon.M..[[WoWEmojis\Omegawow.tga]], x))
    self:AddSmiley(":paladin:", self:TextureString(addon.M..[[WoWEmojis\Paladin.tga]], x))
    self:AddSmiley(":priest:", self:TextureString(addon.M..[[WoWEmojis\Priest.tga]], x))
    self:AddSmiley(":rogue:", self:TextureString(addon.M..[[WoWEmojis\Rogue.tga]], x))
    self:AddSmiley(":samwise:", self:TextureString(addon.M..[[WoWEmojis\Samwise.tga]], x))
    self:AddSmiley(":shaman:", self:TextureString(addon.M..[[WoWEmojis\Shaman.tga]], x))
    self:AddSmiley(":teldrachad:", self:TextureString(addon.M..[[WoWEmojis\TeldraChad.tga]], x))
    self:AddSmiley(":uwutuskarr:", self:TextureString(addon.M..[[WoWEmojis\UwuTuskarr.tga]], x))
    self:AddSmiley(":warcraft:", self:TextureString(addon.M..[[WoWEmojis\Warcraft.tga]], x))
    self:AddSmiley(":warlock:", self:TextureString(addon.M..[[WoWEmojis\Warlock.tga]], x))
    self:AddSmiley(":warrior:", self:TextureString(addon.M..[[WoWEmojis\Warrior.tga]], x))

    -- Epoch Emojis
    self:AddSmiley(":epog:", self:TextureString(addon.M..[[EpochEmojis\Epog.tga]], x))

    -- Gnome Emojis
    self:AddSmiley(":gnomebatman:", self:TextureString(addon.M..[[GnomeEmojis\GnomeBatman.tga]], x))
    self:AddSmiley(":gnomebender:", self:TextureString(addon.M..[[GnomeEmojis\GnomeBender.tga]], x))
    self:AddSmiley(":gnomecandle:", self:TextureString(addon.M..[[GnomeEmojis\GnomeCandle.tga]], x))
    self:AddSmiley(":gnomecandleman:", self:TextureString(addon.M..[[GnomeEmojis\GnomeCandleman.tga]], x))
    self:AddSmiley(":gnomechad:", self:TextureString(addon.M..[[GnomeEmojis\GnomeChad.tga]], x))
    self:AddSmiley(":gnomeclown:", self:TextureString(addon.M..[[GnomeEmojis\GnomeClown.tga]], x))
    self:AddSmiley(":gnomedevil:", self:TextureString(addon.M..[[GnomeEmojis\GnomeDevil.tga]], x))
    self:AddSmiley(":gnomedracula:", self:TextureString(addon.M..[[GnomeEmojis\GnomeDracula.tga]], x))
    self:AddSmiley(":gnomedragonborn:", self:TextureString(addon.M..[[GnomeEmojis\GnomeDragonborn.tga]], x))
    self:AddSmiley(":gnomedruid:", self:TextureString(addon.M..[[GnomeEmojis\GnomeDruid.tga]], x))
    self:AddSmiley(":gnomeexistential:", self:TextureString(addon.M..[[GnomeEmojis\GnomeExistential.tga]], x))
    self:AddSmiley(":gnomeexoticmonk:", self:TextureString(addon.M..[[GnomeEmojis\GnomeExoticMonk.tga]], x))
    self:AddSmiley(":gnomefelguard:", self:TextureString(addon.M..[[GnomeEmojis\GnomeFelguard.tga]], x))
    self:AddSmiley(":gnomeforsaken:", self:TextureString(addon.M..[[GnomeEmojis\GnomeForsaken.tga]], x))
    self:AddSmiley(":gnomegarithos:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGarithos.tga]], x))
    self:AddSmiley(":gnomegoblin:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGoblin.tga]], x))
    self:AddSmiley(":gnomegodfather:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGodfather.tga]], x))
    self:AddSmiley(":gnomegon:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGon.tga]], x))
    self:AddSmiley(":gnomeguts:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGuts.tga]], x))
    self:AddSmiley(":gnomehoplite:", self:TextureString(addon.M..[[GnomeEmojis\GnomeHoplite.tga]], x))
    self:AddSmiley(":gnomeillidan:", self:TextureString(addon.M..[[GnomeEmojis\GnomeIllidan.tga]], x))
    self:AddSmiley(":gnomeironman:", self:TextureString(addon.M..[[GnomeEmojis\GnomeIronman.tga]], x))
    self:AddSmiley(":gnomejoker:", self:TextureString(addon.M..[[GnomeEmojis\GnomeJoker.tga]], x))
    self:AddSmiley(":gnomejudge:", self:TextureString(addon.M..[[GnomeEmojis\GnomeJudge.tga]], x))
    self:AddSmiley(":gnomekratos:", self:TextureString(addon.M..[[GnomeEmojis\GnomeKratos.tga]], x))
    self:AddSmiley(":gnomeloki:", self:TextureString(addon.M..[[GnomeEmojis\GnomeLoki.tga]], x))
    self:AddSmiley(":gnomemage:", self:TextureString(addon.M..[[GnomeEmojis\GnomeMage.tga]], x))
    self:AddSmiley(":gnomemanhattan:", self:TextureString(addon.M..[[GnomeEmojis\GnomeManhattan.tga]], x))
    self:AddSmiley(":gnomemario:", self:TextureString(addon.M..[[GnomeEmojis\GnomeMario.tga]], x))
    self:AddSmiley(":gnomemickey:", self:TextureString(addon.M..[[GnomeEmojis\GnomeMickey.tga]], x))
    self:AddSmiley(":gnomemonk:", self:TextureString(addon.M..[[GnomeEmojis\GnomeMonk.tga]], x))
    self:AddSmiley(":gnomenaga:", self:TextureString(addon.M..[[GnomeEmojis\GnomeNaga.tga]], x))
    self:AddSmiley(":gnomeninja:", self:TextureString(addon.M..[[GnomeEmojis\GnomeNinja.tga]], x))
    self:AddSmiley(":gnomeorc:", self:TextureString(addon.M..[[GnomeEmojis\GnomeOrc.tga]], x))
    self:AddSmiley(":gnomeorochimaru:", self:TextureString(addon.M..[[GnomeEmojis\GnomeOrochimaru.tga]], x))
    self:AddSmiley(":gnomeshaman:", self:TextureString(addon.M..[[GnomeEmojis\GnomeShaman.tga]], x))
    self:AddSmiley(":gnomesonic:", self:TextureString(addon.M..[[GnomeEmojis\GnomeSonic.tga]], x))
    self:AddSmiley(":gnomespace:", self:TextureString(addon.M..[[GnomeEmojis\GnomeSpace.tga]], x))
    self:AddSmiley(":gnomesquidward:", self:TextureString(addon.M..[[GnomeEmojis\GnomeSquidward.tga]], x))
    self:AddSmiley(":gnometemplar:", self:TextureString(addon.M..[[GnomeEmojis\GnomeTemplar.tga]], x))
    self:AddSmiley(":gnomethor:", self:TextureString(addon.M..[[GnomeEmojis\GnomeThor.tga]], x))
    self:AddSmiley(":gnometoji:", self:TextureString(addon.M..[[GnomeEmojis\GnomeToji.tga]], x))
    self:AddSmiley(":gnomeultramarine:", self:TextureString(addon.M..[[GnomeEmojis\GnomeUltramarine.tga]], x))
    self:AddSmiley(":gnomewitcher:", self:TextureString(addon.M..[[GnomeEmojis\GnomeWitcher.tga]], x))
    self:AddSmiley(":gnomewolverine:", self:TextureString(addon.M..[[GnomeEmojis\GnomeWolverine.tga]], x))

    -- Pony Emojis
    self:AddSmiley(":ponysylvy:", self:TextureString(addon.M..[[PonyEmojis\PonySylvy.tga]], x))
    self:AddSmiley(":ponywhitemane:", self:TextureString(addon.M..[[PonyEmojis\PonyWhitemane.tga]], x))
    self:AddSmiley(":ponygarithos:", self:TextureString(addon.M..[[PonyEmojis\PonyGarithos.tga]], x))

    -- Only add text emoticons if enabled
    if ChatEmojisDB.textEmotes then
        self:AddSmiley(">:%(", self:TextureString(addon.M..[[Emojis\Rage.tga]], x))
        self:AddSmiley(":%$", self:TextureString(addon.M..[[Emojis\Blush.tga]], x))
        self:AddSmiley("<\\3", self:TextureString(addon.M..[[Emojis\BrokenHeart.tga]], x))
        self:AddSmiley(":\'%)", self:TextureString(addon.M..[[Emojis\Joy.tga]], x))
        self:AddSmiley(";\'%)", self:TextureString(addon.M..[[Emojis\Joy.tga]], x))
        self:AddSmiley(",,!,,", self:TextureString(addon.M..[[Emojis\MiddleFinger.tga]], x))
        self:AddSmiley("D:<", self:TextureString(addon.M..[[Emojis\Rage.tga]], x))
        self:AddSmiley(":o3", self:TextureString(addon.M..[[Emojis\ScreamCat.tga]], x))
        self:AddSmiley("XP", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.tga]], x))
        self:AddSmiley("8%-%)", self:TextureString(addon.M..[[Emojis\Sunglasses.tga]], x))
        self:AddSmiley("8%)", self:TextureString(addon.M..[[Emojis\Sunglasses.tga]], x))
        self:AddSmiley(":%+1:", self:TextureString(addon.M..[[Emojis\ThumbsUp.tga]], x))
        self:AddSmiley(":;:", self:TextureString(addon.M..[[Emojis\SemiColon.tga]], x))
        self:AddSmiley(";o;", self:TextureString(addon.M..[[Emojis\Sob.tga]], x))
        self:AddSmiley(":%-@", self:TextureString(addon.M..[[Emojis\Angry.tga]], x))
        self:AddSmiley(":@", self:TextureString(addon.M..[[Emojis\Angry.tga]], x))
        self:AddSmiley(":%-%)", self:TextureString(addon.M..[[Emojis\Smile.tga]], x))
        self:AddSmiley(":%)", self:TextureString(addon.M..[[Emojis\Smile.tga]], x))
        self:AddSmiley(":D", self:TextureString(addon.M..[[Emojis\Grin.tga]], x))
        self:AddSmiley(":%-D", self:TextureString(addon.M..[[Emojis\Grin.tga]], x))
        self:AddSmiley(";%-D", self:TextureString(addon.M..[[Emojis\Grin.tga]], x))
        self:AddSmiley(";D", self:TextureString(addon.M..[[Emojis\Grin.tga]], x))
        self:AddSmiley("=D", self:TextureString(addon.M..[[Emojis\Grin.tga]], x))
        self:AddSmiley("xD", self:TextureString(addon.M..[[Emojis\Grin.tga]], x))
        self:AddSmiley("XD", self:TextureString(addon.M..[[Emojis\Grin.tga]], x))
        self:AddSmiley(":%-%(", self:TextureString(addon.M..[[Emojis\SlightFrown.tga]], x))
        self:AddSmiley(":%(", self:TextureString(addon.M..[[Emojis\SlightFrown.tga]], x))
        self:AddSmiley(":o", self:TextureString(addon.M..[[Emojis\OpenMouth.tga]], x))
        self:AddSmiley(":%-o", self:TextureString(addon.M..[[Emojis\OpenMouth.tga]], x))
        self:AddSmiley(":%-O", self:TextureString(addon.M..[[Emojis\OpenMouth.tga]], x))
        self:AddSmiley(":O", self:TextureString(addon.M..[[Emojis\OpenMouth.tga]], x))
        self:AddSmiley(":%-0", self:TextureString(addon.M..[[Emojis\OpenMouth.tga]], x))
        self:AddSmiley(":P", self:TextureString(addon.M..[[Emojis\StuckOutTongue.tga]], x))
        self:AddSmiley(":%-P", self:TextureString(addon.M..[[Emojis\StuckOutTongue.tga]], x))
        self:AddSmiley(":p", self:TextureString(addon.M..[[Emojis\StuckOutTongue.tga]], x))
        self:AddSmiley(":%-p", self:TextureString(addon.M..[[Emojis\StuckOutTongue.tga]], x))
        self:AddSmiley("=P", self:TextureString(addon.M..[[Emojis\StuckOutTongue.tga]], x))
        self:AddSmiley("=p", self:TextureString(addon.M..[[Emojis\StuckOutTongue.tga]], x))
        self:AddSmiley(";%-p", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.tga]], x))
        self:AddSmiley(";p", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.tga]], x))
        self:AddSmiley(";P", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.tga]], x))
        self:AddSmiley(";%-P", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.tga]], x))
        self:AddSmiley(";%-%)", self:TextureString(addon.M..[[Emojis\Wink.tga]], x))
        self:AddSmiley(";%)", self:TextureString(addon.M..[[Emojis\Wink.tga]], x))
        self:AddSmiley(":S", self:TextureString(addon.M..[[Emojis\Smirk.tga]], x))
        self:AddSmiley(":%-S", self:TextureString(addon.M..[[Emojis\Smirk.tga]], x))
        self:AddSmiley(":,%(", self:TextureString(addon.M..[[Emojis\Cry.tga]], x))
        self:AddSmiley(":,%-%(", self:TextureString(addon.M..[[Emojis\Cry.tga]], x))
        self:AddSmiley(":\'%(", self:TextureString(addon.M..[[Emojis\Cry.tga]], x))
        self:AddSmiley(":\'%-%(", self:TextureString(addon.M..[[Emojis\Cry.tga]], x))
        self:AddSmiley(":F", self:TextureString(addon.M..[[Emojis\MiddleFinger.tga]], x))
        self:AddSmiley("<3", self:TextureString(addon.M..[[Emojis\Heart.tga]], x))
        self:AddSmiley("</3", self:TextureString(addon.M..[[Emojis\BrokenHeart.tga]], x))
    end
end

-- Function to add emoji mappings
function addon:AddSmiley(key, texture)
    if key and (type(key) == "string") and texture then
        self.Smileys[key] = texture
    end
end

-- Function to remove emoji mappings if needed
function addon:RemoveSmiley(key)
    if key and (type(key) == "string") then
        self.Smileys[key] = nil
    end
end

-- Update emoji mappings with current size
function addon:UpdateEmojiMappings()
    wipe(self.Smileys)
    self:SetupDefaultEmojis()
end

-- Helper to get emoji category
function addon:GetEmojiCategory(emojiName)
    local emojiCode = ":" .. emojiName .. ":"

    local texture = self.Smileys[emojiCode]
    if not texture then
        return "Emojis"
    end

    local categoryFolder = string.match(texture, "Media\\([^\\]+)\\")

    if categoryFolder then
        return categoryFolder
    end

    return "Emojis"
end
